### ISSUE TITLE
Make shopping page live

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/oregonsadventurecoast.com#141] opened 2020-10-19 12:52 UTC
> We have finished entering all the data for the Shopping page (not the shopping cart) and are ready to have that page created. This should have similar structure and functionality as the Lodging & Dining pages. There is a shopping page currently - and we don’t want to loose the text on that page. I wonder if you can just make a duplicate of it before you change it?

> Let me know if there is anything else you need from me to push this live.

**Comment by regisphilibert** [comment] 2020-10-20 17:49
duplicate of #116

**Closed by regisphilibert** 2020-10-20 17:49 UTC
